cap label var d_leave_ind "Fraction of individuals that ever left the household"
cap label var d_violence "Dummy presence of violence (presence=1)"
cap label var deathwounded "Sum of dead and wounded by 100 people"
cap label var leave "Fraction of years when individual left the household"
cap label var hh_d_violence "Dummy presence of violence"
cap label var hh_deathwounded "Sum of dead and wounded"
cap label var d_leave_hh "At least 1 person left the household in a given year (yes=1)"
cap label var leave_hh "Average number of people leaving the household in a given year"

cap label var hh_cff_income "Average annual coffee income"
cap label var  hh_livestock "Average annual livestock holdings (in tlu)*"
cap label var sk_vl_rob_money "Theft of money (yes=1) for a household in a given year"
cap label var  sk_vl_rob_product "Theft of crops (yes=1) for a household in a given year"
cap label var sk_vl_rob_goods  "Theft or destruction of goods (yes=1) for a household in a given year"
cap label var sk_vl_rob_destruction "Destruction of house (yes=1) for a household in a given year"
cap label var  sk_vl_rob_land "Loss of land (yes=1) for a household in a given year"

cap label var hh_sk_vl_rob_money "Household ever experienced theft of money"
cap label var  hh_sk_vl_rob_product "Household ever experienced theft of crops"
cap label var hh_sk_vl_rob_goods  "Household ever experienced theft or destruction of good"
cap label var hh_sk_vl_rob_destruction "Household ever experienced destruction of house"
cap label var  hh_sk_vl_rob_land "Household ever experienced loss of land"

cap label var v_d_violence "Fraction of years when village experienced violence"
cap label var v_deathwounded "Sum of dead and wounded"
cap label var v1_d_violence "Fraction of villages that ever experienced violence"

cap label var lag_d_violence "Lag dummy violence (presence=1)"
cap label var deathwounded_100 "Sum of dead and wounded (by 100 people)"
cap label var lag_deathwounded_100 "Lag sum of dead and wounded (by 100 people)"

cap labe var leave_hh_t "Number of member of household that leave"
cap label var d_leave_hh_t "Fraction of individuals that ever left the household"

cap labe var a_coffee_produc_97 "Area (ha) of coffee production in a productive age ($<= 8$ years old) in 1997"
cap labe var density_97 "Crop Density (trees x ha) (1997)"
cap labe var lotes_97 "Number of coffee fields (1997)"
